http://localhost:3000/users/

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Biden",
    "handle": "@potus",
    "password": "DrJill"
}

###

http://localhost:3000/posts/2

###
http://localhost:3000/users/login

{
    "handle" : "",
    "password": 
}